/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import platoon.World

@RunWith(XtextRunner)
@InjectWith(PlatoonInjectorProvider)
class PlatoonParsingTest{

	@Inject
	ParseHelper<World> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
