/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext.ui;

import com.google.inject.Injector;
import nl.tue.glt.xtext.platoon.ui.internal.PlatoonActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlatoonExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlatoonActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlatoonActivator.getInstance().getInjector(PlatoonActivator.NL_TUE_GLT_XTEXT_PLATOON);
	}
	
}
