/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext.ui;

import nl.tue.glt.xtext.ui.AbstractBoundingBoxUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BoundingBoxUiModule extends AbstractBoundingBoxUiModule {
  public BoundingBoxUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
