/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext.parser.antlr;

import com.google.inject.Inject;
import nl.tue.glt.xtext.parser.antlr.internal.InternalPlatoonParser;
import nl.tue.glt.xtext.services.PlatoonGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PlatoonParser extends AbstractAntlrParser {

	@Inject
	private PlatoonGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPlatoonParser createParser(XtextTokenStream stream) {
		return new InternalPlatoonParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "World";
	}

	public PlatoonGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PlatoonGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
