/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext;

import nl.tue.glt.xtext.AbstractPlatoonRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlatoonRuntimeModule extends AbstractPlatoonRuntimeModule {
}
