/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext;

import nl.tue.glt.xtext.PlatoonStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlatoonStandaloneSetup extends PlatoonStandaloneSetupGenerated {
  public static void doSetup() {
    PlatoonStandaloneSetup _platoonStandaloneSetup = new PlatoonStandaloneSetup();
    _platoonStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
