/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BoundingBoxGrammarAccess extends AbstractGrammarElementFinder {
	
	public class WorldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.tue.glt.xtext.BoundingBox.World");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWorldAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoxKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMoveCommandsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMoveCommandsMoveParserRuleCall_2_0 = (RuleCall)cMoveCommandsAssignment_2.eContents().get(0);
		
		//World:
		//	{World}
		//	'Box:'
		//	moveCommands+=Move+;
		@Override public ParserRule getRule() { return rule; }
		
		//{World} 'Box:' moveCommands+=Move+
		public Group getGroup() { return cGroup; }
		
		//{World}
		public Action getWorldAction_0() { return cWorldAction_0; }
		
		//'Box:'
		public Keyword getBoxKeyword_1() { return cBoxKeyword_1; }
		
		//moveCommands+=Move+
		public Assignment getMoveCommandsAssignment_2() { return cMoveCommandsAssignment_2; }
		
		//Move
		public RuleCall getMoveCommandsMoveParserRuleCall_2_0() { return cMoveCommandsMoveParserRuleCall_2_0; }
	}
	public class MoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.tue.glt.xtext.BoundingBox.Move");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cMoveUpParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cMoveDownParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cMoveLeftParserRuleCall_0_2 = (RuleCall)cAlternatives_0.eContents().get(2);
		private final RuleCall cMoveRightParserRuleCall_0_3 = (RuleCall)cAlternatives_0.eContents().get(3);
		private final Assignment cDistanceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDistanceEIntParserRuleCall_1_0 = (RuleCall)cDistanceAssignment_1.eContents().get(0);
		
		//Move:
		//	(MoveUp | MoveDown | MoveLeft | MoveRight) distance=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//(MoveUp | MoveDown | MoveLeft | MoveRight) distance=EInt
		public Group getGroup() { return cGroup; }
		
		//(MoveUp | MoveDown | MoveLeft | MoveRight)
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//MoveUp
		public RuleCall getMoveUpParserRuleCall_0_0() { return cMoveUpParserRuleCall_0_0; }
		
		//MoveDown
		public RuleCall getMoveDownParserRuleCall_0_1() { return cMoveDownParserRuleCall_0_1; }
		
		//MoveLeft
		public RuleCall getMoveLeftParserRuleCall_0_2() { return cMoveLeftParserRuleCall_0_2; }
		
		//MoveRight
		public RuleCall getMoveRightParserRuleCall_0_3() { return cMoveRightParserRuleCall_0_3; }
		
		//distance=EInt
		public Assignment getDistanceAssignment_1() { return cDistanceAssignment_1; }
		
		//EInt
		public RuleCall getDistanceEIntParserRuleCall_1_0() { return cDistanceEIntParserRuleCall_1_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.tue.glt.xtext.BoundingBox.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class MoveUpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.tue.glt.xtext.BoundingBox.MoveUp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveUpAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUpKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//MoveUp:
		//	{MoveUp}
		//	'up';
		@Override public ParserRule getRule() { return rule; }
		
		//{MoveUp} 'up'
		public Group getGroup() { return cGroup; }
		
		//{MoveUp}
		public Action getMoveUpAction_0() { return cMoveUpAction_0; }
		
		//'up'
		public Keyword getUpKeyword_1() { return cUpKeyword_1; }
	}
	public class MoveDownElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.tue.glt.xtext.BoundingBox.MoveDown");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveDownAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDownKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//MoveDown:
		//	{MoveDown}
		//	'down';
		@Override public ParserRule getRule() { return rule; }
		
		//{MoveDown} 'down'
		public Group getGroup() { return cGroup; }
		
		//{MoveDown}
		public Action getMoveDownAction_0() { return cMoveDownAction_0; }
		
		//'down'
		public Keyword getDownKeyword_1() { return cDownKeyword_1; }
	}
	public class MoveLeftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.tue.glt.xtext.BoundingBox.MoveLeft");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveLeftAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//MoveLeft:
		//	{MoveLeft}
		//	'left';
		@Override public ParserRule getRule() { return rule; }
		
		//{MoveLeft} 'left'
		public Group getGroup() { return cGroup; }
		
		//{MoveLeft}
		public Action getMoveLeftAction_0() { return cMoveLeftAction_0; }
		
		//'left'
		public Keyword getLeftKeyword_1() { return cLeftKeyword_1; }
	}
	public class MoveRightElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nl.tue.glt.xtext.BoundingBox.MoveRight");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveRightAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRightKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//MoveRight:
		//	{MoveRight}
		//	'right';
		@Override public ParserRule getRule() { return rule; }
		
		//{MoveRight} 'right'
		public Group getGroup() { return cGroup; }
		
		//{MoveRight}
		public Action getMoveRightAction_0() { return cMoveRightAction_0; }
		
		//'right'
		public Keyword getRightKeyword_1() { return cRightKeyword_1; }
	}
	
	
	private final WorldElements pWorld;
	private final MoveElements pMove;
	private final EIntElements pEInt;
	private final MoveUpElements pMoveUp;
	private final MoveDownElements pMoveDown;
	private final MoveLeftElements pMoveLeft;
	private final MoveRightElements pMoveRight;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BoundingBoxGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pWorld = new WorldElements();
		this.pMove = new MoveElements();
		this.pEInt = new EIntElements();
		this.pMoveUp = new MoveUpElements();
		this.pMoveDown = new MoveDownElements();
		this.pMoveLeft = new MoveLeftElements();
		this.pMoveRight = new MoveRightElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("nl.tue.glt.xtext.BoundingBox".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//World:
	//	{World}
	//	'Box:'
	//	moveCommands+=Move+;
	public WorldElements getWorldAccess() {
		return pWorld;
	}
	
	public ParserRule getWorldRule() {
		return getWorldAccess().getRule();
	}
	
	//Move:
	//	(MoveUp | MoveDown | MoveLeft | MoveRight) distance=EInt;
	public MoveElements getMoveAccess() {
		return pMove;
	}
	
	public ParserRule getMoveRule() {
		return getMoveAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//MoveUp:
	//	{MoveUp}
	//	'up';
	public MoveUpElements getMoveUpAccess() {
		return pMoveUp;
	}
	
	public ParserRule getMoveUpRule() {
		return getMoveUpAccess().getRule();
	}
	
	//MoveDown:
	//	{MoveDown}
	//	'down';
	public MoveDownElements getMoveDownAccess() {
		return pMoveDown;
	}
	
	public ParserRule getMoveDownRule() {
		return getMoveDownAccess().getRule();
	}
	
	//MoveLeft:
	//	{MoveLeft}
	//	'left';
	public MoveLeftElements getMoveLeftAccess() {
		return pMoveLeft;
	}
	
	public ParserRule getMoveLeftRule() {
		return getMoveLeftAccess().getRule();
	}
	
	//MoveRight:
	//	{MoveRight}
	//	'right';
	public MoveRightElements getMoveRightAccess() {
		return pMoveRight;
	}
	
	public ParserRule getMoveRightRule() {
		return getMoveRightAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
