/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import nl.tue.glt.xtext.services.PlatoonGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import platoon.Constraints;
import platoon.FollowVehicle;
import platoon.ForwardCommand;
import platoon.HeadwayConstraint;
import platoon.LeadingVehicle;
import platoon.Platoon;
import platoon.PlatoonPackage;
import platoon.Route;
import platoon.TurnCommand;
import platoon.World;

@SuppressWarnings("all")
public class PlatoonSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private PlatoonGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PlatoonPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PlatoonPackage.CONSTRAINTS:
				sequence_Constraints(context, (Constraints) semanticObject); 
				return; 
			case PlatoonPackage.FOLLOW_VEHICLE:
				sequence_FollowVehicle(context, (FollowVehicle) semanticObject); 
				return; 
			case PlatoonPackage.FORWARD_COMMAND:
				sequence_ForwardCommand(context, (ForwardCommand) semanticObject); 
				return; 
			case PlatoonPackage.HEADWAY_CONSTRAINT:
				sequence_HeadwayConstraint(context, (HeadwayConstraint) semanticObject); 
				return; 
			case PlatoonPackage.LEADING_VEHICLE:
				sequence_LeadingVehicle(context, (LeadingVehicle) semanticObject); 
				return; 
			case PlatoonPackage.PLATOON:
				sequence_Platoon(context, (Platoon) semanticObject); 
				return; 
			case PlatoonPackage.ROUTE:
				sequence_Route(context, (Route) semanticObject); 
				return; 
			case PlatoonPackage.TURN_COMMAND:
				sequence_TurnCommand(context, (TurnCommand) semanticObject); 
				return; 
			case PlatoonPackage.WORLD:
				sequence_World(context, (World) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Constraints returns Constraints
	 *
	 * Constraint:
	 *     (constraints+=Constraint constraints+=Constraint*)
	 */
	protected void sequence_Constraints(ISerializationContext context, Constraints semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Vehicle returns FollowVehicle
	 *     FollowVehicle returns FollowVehicle
	 *
	 * Constraint:
	 *     (id=EString follows=[Vehicle|EString])
	 */
	protected void sequence_FollowVehicle(ISerializationContext context, FollowVehicle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.VEHICLE__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.VEHICLE__ID));
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.FOLLOW_VEHICLE__FOLLOWS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.FOLLOW_VEHICLE__FOLLOWS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFollowVehicleAccess().getIdEStringParserRuleCall_2_0(), semanticObject.getId());
		feeder.accept(grammarAccess.getFollowVehicleAccess().getFollowsVehicleEStringParserRuleCall_5_0_1(), semanticObject.getFollows());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Command returns ForwardCommand
	 *     ForwardCommand returns ForwardCommand
	 *
	 * Constraint:
	 *     distance=INT
	 */
	protected void sequence_ForwardCommand(ISerializationContext context, ForwardCommand semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.FORWARD_COMMAND__DISTANCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.FORWARD_COMMAND__DISTANCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getForwardCommandAccess().getDistanceINTTerminalRuleCall_3_0(), semanticObject.getDistance());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Constraint returns HeadwayConstraint
	 *     HeadwayConstraint returns HeadwayConstraint
	 *
	 * Constraint:
	 *     (min=INT max=INT)
	 */
	protected void sequence_HeadwayConstraint(ISerializationContext context, HeadwayConstraint semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.HEADWAY_CONSTRAINT__MIN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.HEADWAY_CONSTRAINT__MIN));
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.HEADWAY_CONSTRAINT__MAX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.HEADWAY_CONSTRAINT__MAX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHeadwayConstraintAccess().getMinINTTerminalRuleCall_1_0(), semanticObject.getMin());
		feeder.accept(grammarAccess.getHeadwayConstraintAccess().getMaxINTTerminalRuleCall_5_0(), semanticObject.getMax());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Vehicle returns LeadingVehicle
	 *     LeadingVehicle returns LeadingVehicle
	 *
	 * Constraint:
	 *     (id=EString route=[Route|EString])
	 */
	protected void sequence_LeadingVehicle(ISerializationContext context, LeadingVehicle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.VEHICLE__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.VEHICLE__ID));
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.LEADING_VEHICLE__ROUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.LEADING_VEHICLE__ROUTE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLeadingVehicleAccess().getIdEStringParserRuleCall_2_0(), semanticObject.getId());
		feeder.accept(grammarAccess.getLeadingVehicleAccess().getRouteRouteEStringParserRuleCall_4_0_1(), semanticObject.getRoute());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Platoon returns Platoon
	 *
	 * Constraint:
	 *     (LV=LeadingVehicle FV+=FollowVehicle?)
	 */
	protected void sequence_Platoon(ISerializationContext context, Platoon semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Route returns Route
	 *
	 * Constraint:
	 *     (id=EString commands+=Command commands+=Command*)
	 */
	protected void sequence_Route(ISerializationContext context, Route semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Command returns TurnCommand
	 *     TurnCommand returns TurnCommand
	 *
	 * Constraint:
	 *     direction=Direction
	 */
	protected void sequence_TurnCommand(ISerializationContext context, TurnCommand semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.TURN_COMMAND__DIRECTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.TURN_COMMAND__DIRECTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTurnCommandAccess().getDirectionDirectionParserRuleCall_2_0(), semanticObject.getDirection());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     World returns World
	 *
	 * Constraint:
	 *     (platoon=Platoon route=Route constraints=Constraints)
	 */
	protected void sequence_World(ISerializationContext context, World semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.WORLD__PLATOON) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.WORLD__PLATOON));
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.WORLD__ROUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.WORLD__ROUTE));
			if (transientValues.isValueTransient(semanticObject, PlatoonPackage.Literals.WORLD__CONSTRAINTS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, PlatoonPackage.Literals.WORLD__CONSTRAINTS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWorldAccess().getPlatoonPlatoonParserRuleCall_1_0(), semanticObject.getPlatoon());
		feeder.accept(grammarAccess.getWorldAccess().getRouteRouteParserRuleCall_2_0(), semanticObject.getRoute());
		feeder.accept(grammarAccess.getWorldAccess().getConstraintsConstraintsParserRuleCall_3_0(), semanticObject.getConstraints());
		feeder.finish();
	}
	
	
}
