/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.xtext.ui.tests;

import com.google.inject.Injector;
import nl.tue.glt.xtext.platoon.ui.internal.PlatoonActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class PlatoonUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PlatoonActivator.getInstance().getInjector("nl.tue.glt.xtext.Platoon");
	}

}
